=== azaad1203/LIBT-project/wwwroot/WEB-INF/xml/schema/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="record" type="recordType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="recordType">
		<xs:sequence>
			   <xs:element name="column" type="columnType" minOccurs="0" maxOccurs="unbounded"/>		
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== azaad1203/LIBT-project/wwwroot/WEB-INF/xml/question.xml
<?xml version="1.0" encoding="UTF-8"?>
<table xsi:schemaLocation="schema/table.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<record>
	<column name="id">56e1924d-443c-4d86-a301-797fa77ea656</column>
	<column name="name">Peggy R. Seay</column>
	<column name="email">peggyrseay@teleworm.us</column>
	<column name="title">How to start a web sever?</column>
	<column name="postDate">2013-02-26 11:02:00 PM</column>
	<column name="description">I have download the appache tomcat from the official website, and I also got ecilpse. But how do I use ecilpse to launch the tomcat?</column>
	<column name="modifiedDate">2013-02-26 11:02:00 PM</column>
	<column name="updateDate">2013-02-26 11:02:00 PM</column>
	<column name="modified">0</column>
</record>
<record>
	<column name="id">0f123a02-5c78-4781-80c9-7dc84eb38168</column>
	<column name="name">James E. Rachel</column>
	<column name="email">jameserachel@dayrep.com</column>
	<column name="title">In prolog, how do I test if two lists are equal?</column>
	<column name="postDate">2013-02-26 11:10:00 PM</column>
	<column name="description">Since the equal sign(=:=) is not applicable to list, I would like to ask for a way to accomplish this.</column>
	<column name="modifiedDate">2013-02-26 11:10:00 PM</column>
	<column name="updateDate">2013-02-26 11:10:00 PM</column>
	<column name="modified">0</column>
</record>
<record>
	<column name="id">c7d6f53d-2918-4db2-9380-a5d54b4f91ee</column>
	<column name="name">John D. McPeek</column>
	<column name="email">johndmcpeek@armyspy.com</column>
	<column name="title">Can you postpone the deadline of group project? </column>
	<column name="postDate">2013-02-26 11:11:00 PM</column>
	<column name="description">Just Ask :)</column>
	<column name="modifiedDate">2013-02-28 3:43:11 AM</column>
	<column name="updateDate">2013-03-31 8:05:18 PM</column>
	<column name="modified">0</column>
	<column name="answerId">0730b71a-4a8e-44d8-ba2d-6b2fb66e9659</column></record>
<record>
	<column name="id">c0cee805-0924-4c87-9fcf-68bfb1b37ccd</column>
	<column name="name">Timothy P. Winans</column>
	<column name="email">timothypwinans@dayrep.com</column>
	<column name="title">Is it possible to retake Java?</column>
	<column name="postDate">2013-02-27 4:51:00 AM</column>
	<column name="description">I am not really confident on java. If the java exam is failed, what should I do?</column>
	<column name="modifiedDate">2013-03-31 8:05:47 PM</column>
	<column name="updateDate">2013-03-31 8:05:47 PM</column>
	<column name="modified">1</column>
</record>
<record><column name="id">ef929199-3249-4b33-98ce-eb4bb2555f25</column><column name="title">When are Introductorey programming Tutor lessons?</column><column name="email">abdul@hotmail.com</column><column name="postDate">2013-03-31 9:38:16 PM</column><column name="description">Java is different from python. Python is easy to use, but java is not. Sometimes, a very easy task in python would become difficult in java. For example, in order sort an array, we must import a class called Arrays. Using its static method sort&amp;#40;&amp;#41;, the array could be sort. However in python, we only need to call the sort method from the array.&#13;
&#13;
Therefore, I need some more help in java.</column><column name="name">abdul</column><column name="answerId">6e74ce06-f4a7-4ab3-9bb3-8a3a1dde5a91</column><column name="updateDate">2013-03-31 10:17:12 PM</column><column name="modifiedDate">2013-03-31 10:09:54 PM</column><column name="modified">1</column></record><record><column name="id">fd92bd5a-22f2-4476-bf7b-21e56f2c6c67</column><column name="title">&amp;lt;b&amp;gt;When are Introductorey programming Tutor lessons?&amp;lt;&amp;#x2F;b&amp;gt;</column><column name="email">abdul@hotmail.com</column><column name="postDate">2013-03-31 9:39:30 PM</column><column name="description"><![CDATA[&lt;div style=&quot;background-color:#000&quot;&gt;
As stated.
&lt;&#x2F;div&gt;]]></column><column name="name">Abdul</column><column name="answerId"/><column name="updateDate">2013-03-31 9:39:30 PM</column><column name="modifiedDate">2013-03-31 9:39:30 PM</column><column name="modified">0</column></record></table>

=== azaad1203/LIBT-project/wwwroot/WEB-INF/xml/answer.xml
<?xml version="1.0" encoding="UTF-8"?>
<table xsi:schemaLocation="schema/table.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<record>
<column name="id">0730b71a-4a8e-44d8-ba2d-6b2fb66e9659</column>
<column name="postDate">2013-02-28 5:43:11 AM</column>
<column name="description">The deadline is postponed to 2013&amp;#x2F;3&amp;#x2F;31. Good luck !</column>
<column name="modifiedDate">2013-03-31 8:05:18 PM</column>
<column name="updateDate">2013-02-28 5:43:11 AM</column>
<column name="modified">1</column>
</record>
<record><column name="id">6e74ce06-f4a7-4ab3-9bb3-8a3a1dde5a91</column><column name="postDate">2013-03-31 10:16:24 PM</column><column name="description"><![CDATA[&lt;div onclick=&quot;alert&#40;&quot;haha&quot;&#41;&quot;&gt;
 Due to LIBT policy, apart from regular lessons, not tutor lessons could be launched.
 &lt;&#x2F;div&gt;]]></column><column name="modifiedDate">2013-03-31 10:17:12 PM</column><column name="modified">1</column></record></table>
